end/project1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include


from django.http import HttpResponse


def index(request):
    return HttpResponse("这里是首页")


def list(request):
    return HttpResponse("这里是列表页")


def jsondata(request):
    return HttpResponse("{'name':'cxw','age':23}")
# 路由地址 每一个地址均需要绑定视图函数 视图函数给予页面返回
# mvt v 视图函数    作用：接受请求 处理数据 返回响应

urlpatterns = [
    path('admin/', admin.site.urls),
    # 1.使用path将bookset的路由进行包含
    path('polls/', include('polls.urls', namespace='polls')),
    path('download/', include('download.urls', namespace='download')),
    path('', include('bookset.urls', namespace='bookset')),

]

end/project1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # 如果在正则表达式中有正则分组  那么在视图中必须得有响应的形参
    # 如果正则分组有别名 那么形参名一定要和正则分组别名一致
    url(r'^detail/(?P<qid>\d+)/$',views.detail,name='detail'),
    url(r'^result/(\d+)/$',views.result,name='result'),
    url(r'^login/$',views.login,name='login'),
    url(r'^regist/$',views.regist,name='regist'),
    url(r'^logout/$',views.logout,name='logout')

    # url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^detail/(?P<qid>\d+)/$',views.DetailView.as_view(),name='detail'),
    # url(r'^result/(\d+)/$',views.ResultView.as_view(),name='result')
]

end/project1/bookdemo/polls/models.py
from django.db import models
# Create your models here.
# 使用django自带的用户系统
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    """
    自定义用户类继承django自带用户系统
    """
    telephone = models.CharField(max_length=20,verbose_name="手机号")
    questions = models.ManyToManyField('Question')

class Question(models.Model):
    """
    投票问题类
    """
    title = models.CharField(max_length=50, verbose_name="投票问题")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "投票表"
        verbose_name_plural = verbose_name
        ordering = ["-create_time"]

class Choices(models.Model):
    """
    投票选项类
    """
    content = models.CharField(max_length=50,verbose_name="选项")
    votes = models.PositiveIntegerField(verbose_name="得票数")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='choices',verbose_name="所属问题")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "选项表"
        verbose_name_plural = "选项表"
        ordering = ["-create_time"]

end/project1/bookdemo/polls/forms.py
from django import forms

from .models import User


class LoginForm(forms.Form):
    """
    定义一个登录表单生成html登录表单
    """
    username = forms.CharField(max_length=150,min_length=3,label="请输入用户名",help_text="用户名最少3位数，最大150")
    password = forms.CharField(max_length=150,min_length=3,label="请输入密码",help_text="密码最少3位数，最大150",widget=forms.PasswordInput)


class RegistForm(forms.ModelForm):
    password2 = forms.CharField(widget=forms.PasswordInput,label="重复密码")
    class Meta:
        model = User
        fields = {'username', 'password'}
        labels = {
            'username':'用户名',
            'password':'password'
        }
        help_texts = {
            'username':'最小为3，最大为50',
            'password':'最小为3，最大为50'
        }
        widgets = {
            'password':forms.PasswordInput()
        }

end/project1/bookdemo/polls/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,JsonResponse,FileResponse
from .models import *
from .forms import *
# Create your views here.
from django.views.generic import View,TemplateView,ListView,CreateView,DeleteView,UpdateView,DetailView as DV
# View类为所有的视图响应类的父类
from django.contrib.auth import authenticate,login as lin,logout as lot


def index(request):
    print("====================")
    print(request.GET.get("hobbys"))
    print(request.GET.getlist("hobbys"))
    # print(request.META.get('HTTP_X_REQUESTED_WITH'))
    # print(dir(request))


    questions = Question.objects.all()
    # 使用render发起一次请求
    return render(request,'polls/index.html',{"questions":questions})
    # return HttpResponse("首页")
    # return JsonResponse({"name":"zzy"})

    # return FileResponse(open("static/img/公众号.jpg","rb"),content_type="image/png",filename="aa.png",as_attachment=True)


# 基于CBV的形式实现首页
class IndexView(ListView):
    # 方法二、继承ListView
    # template_name指明使用的模板
    template_name = "polls/index.html"
    # queryset 指明返回的结果列表
    queryset = Question.objects.all()
    # context_object_name 指明返回字典参数的健
    context_object_name = "questions"

    # 方法一、继承的TemplateView
    # template_name = "polls/index.html"
    # def get_context_data(self, **kwargs):
    #     return {"questions":Question.objects.all()}
def detail(request, qid):
    print(qid, "+++")
    if request.method == "GET":
        print("当前用户",request.user.username)
        if request.user and request.user.username != "":
            # 已经登录过了
            # print("++",request.user.questions,type(request.user.questions.all()))
            try:
                question = Question.objects.get(id=qid)
                if question in request.user.questions.all():
                    print("已经投过票")
                    url = reverse("polls:result",args=(qid))
                    return redirect(to=url)
                else:
                    try:
                        # question = Question.objects.get(id=qid)
                        print(question, "--")
                        # 使用render发起一起请求
                        return render(request, 'polls/detail.html', {"question": question})

                    except Exception as e:
                        print(e, "--")
                        return HttpResponse("问题不合法")

            except Exception as e:
                print(e,"-----")

        else:
            url = reverse("polls:login")+"?next=/polls/detail/"+qid+"/"
            return redirect(to=url)
    elif request.method == "POST":
        choiceid = request.POST.get("num")
        try:
            choice = Choices.objects.get(id=choiceid)
            choice.votes+=1
            choice.save()

            request.user.questions.add( Question.objects.get(id=qid) )
            # 返回当前投票问题的投票结果页
            url = reverse("polls:result", args=(qid,))
            # 投票成功 返回投票结果

            # redirect其实没有真正的返回内容   而是让浏览器重新请求一个地址
            # 不能反复刷新post的结果
            # question = Question.objects.get(id=qid)
            # 错误的结局  刷新页面导致数据出错
            # return render(request,'polls/result.html',{"question":question})
            return redirect(to=url)
            # return HttpResponse("投票成功了")  #接受了详情页的post请求
            # return HttpResponse("现在我代替你进入到了投票结果页")  # 接受了结果页的get请求

        except:
            return HttpResponse("选项不合法")
    # return HttpResponse("详情页"+qid)

class DetailView(View):
    def get(self,request,qid):
        try:
            question = Question.objects.get(id=qid)
            print(question, "--")
            # 使用render发起一起请求
            return render(request, 'polls/detail.html', {"question": question})

        except Exception as e:
            print(e)
            return HttpResponse("问题不合法")
    def post(self,request,qid):
        choiceid = request.POST.get("num")
        try:
            choice = Choices.objects.get(id=choiceid)
            choice.votes += 1
            choice.save()
            # 返回当前投票问题的投票结果页
            url = reverse("polls:result", args=(qid,))
            # 投票成功 返回投票结果

            # redirect其实没有真正的返回内容   而是让浏览器重新请求一个地址
            # 不能反复刷新post的结果
            # question = Question.objects.get(id=qid)
            # 错误的结局  刷新页面导致数据出错
            # return render(request,'polls/result.html',{"question":question})
            return redirect(to=url)
            # return HttpResponse("投票成功了")  #接受了详情页的post请求
            # return HttpResponse("现在我代替你进入到了投票结果页")  # 接受了结果页的get请求

        except Exception as e:
            print(e)
            return HttpResponse("选项不合法")

def result(request,qid):

    try:
        question = Question.objects.get(id=qid)
        return render(request,'polls/result.html',{"question":question})
    except Exception as e:
        print(e)
        return HttpResponse("问题不合法")

class ResultView(View):
    # 方法一 继承View
    def get(self,request,qid):
        try:
            question = Question.objects.get(id=qid)
            return render(request, 'polls/result.html', {"question": question})
        except Exception as e:
            print(e)
            return HttpResponse("问题不合法")


def login(request):
    if request.method == "GET":
        # 第一种方法自己写一个html文件用于显示
        # return render(request,'polls/login.html')
        # 方法2:使用Django自带的表单类来生成HTML文件
        lf = LoginForm()
        return render(request, 'polls/login.html', {"lf": lf})
    elif request.method == "POST":
        # 方法1
        # username = request.POST.get("username")
        # password = request.POST.get("password")
        # 方法2
        lf = LoginForm(data=request.POST)
        if lf.is_valid():
            username = lf.cleaned_data["username"]
            password = lf.cleaned_data["password"]
        # ---------------方法2结束--------------------
        # 可以使用django自带的用户认证系统  认证成功返回用户 失败返回None
            user = authenticate(username=username,password=password)
        # 调用django登录方法  其实是为了生成cookie
            if user:
                lin(request, user)
                next = request.GET.get("next")
                print("取得next参数为",next)
                if next:
                    url = next
                else:
                    url = reverse("polls:index")
                return redirect(to=url)
            else:
                # url = reverse("polls:login")
                # return redirect(to=url)
                return render(request, 'polls/login.html', {"error": "用户名和密码不匹配","lf":lf})
        else:
            return HttpResponse("未知错误")
def regist(request):
    if request.method == "GET":
        rf = RegistForm()
        return render(request, 'polls/regist.html', {"rf": rf})
        # 方法1
        # return render(request,'polls/regist.html')
    elif request.method == "POST":
        # 方法1:
        # username = request.POST.get("username")
        # password = request.POST.get("password")
        # password2 = request.POST.get("password2")
        # 方法3：
        rf = RegistForm(data=request.POST)
        if rf.is_valid():
            username = rf.cleaned_data["username"]
            password = rf.cleaned_data["password"]
            password2 = rf.cleaned_data["password2"]
            # if User.objects.get(username=username).count()>0:
            #     # return HttpResponse("用户名已存在")
            #     return render(request, 'polls/regist.html',{"error":"用户名已存在","rf":rf})
            # else:
            if password == password2:
                User.objects.create_user(username=username, password=password)
                url = reverse("polls:login")
                return redirect(to=url)
            else:
                # return HttpResponse("密码不一致")
                return render(request, 'polls/regist.html', {"error": "密码不一致","rf":rf})
        else:
            return render(request, 'polls/regist.html', {"error": "密码不一致或用户名已存在","rf":rf})





def logout(request):
    # 调用django的登出方法 目的是为了删除cookie
    lot(request)
    url = reverse("polls:index")
    return redirect(to=url)

end/project1/bookdemo/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            这里是标题
        {% endblock %}
    </title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
       {% block header %}
            <div>
                {% if request.user and request.user.username != '' %}
                   用户名： {{request.user.username}} <a href="{% url 'polls:logout' %}">退出</a>
                {% else %}
                    <a href="{% url 'polls:login' %}">登录</a> <a href="{% url 'polls:regist' %}">注册</a>
                {% endif %}


            </div>



        {% endblock %}


        {% block body %}
            这里是身体
        {% endblock %}

        {% block footer %}
            这里是底部
        {% endblock %}
    </div>
</body>
</html>

end/project1/bookdemo/templates/polls/detail.html
{% extends 'polls/base.html' %}
        {% block title %}
            投票详情
        {% endblock %}
        {% block body %}
             <h2> 投票的问题是： {{question.title}} </h2>

        <ul>
            <h3>选项有</h3>

            <form action="#" method="post">
                {# {% csrf_token %} 这个标签可以请求获取csrftoken信息 #}
                {% csrf_token %}
                {% for c in question.choices.all %}
                    {% if forloop.counter == 1 %}
                        <li><input type="radio" checked name="num" value="{{c.id}}">     {{c.content}}</li>
                    {% else %}
                        <li><input type="radio"  name="num" value="{{c.id}}">     {{c.content}}</li>
                    {% endif %}

                {% endfor %}

                <input type="submit" value="投票">
            </form>
        </ul>

        <a href="{% url 'polls:index' %}">返回</a>
        {% endblock %}

end/project1/bookdemo/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %}
    投票首页
{% endblock %}

{% block body %}
        <h2>投票问题列表</h2>
        <ul>
            {% for q in questions %}
                <li><a href="{% url 'polls:detail' q.id %}"> {{forloop.counter}} . {{q.title}}</a> </li>
            {% endfor %}
        </ul>
        {# {% include 'polls/other.html' %} #}
{% endblock %}

end/project1/bookdemo/templates/polls/login.html
{% extends 'polls/base.html' %}
{% block title %}
    登录
{% endblock %}

{% block body %}
{% comment %}
<form action="#" method="post">
    {% csrf_token %}
    用户名: <input type="text" name="username" required>
    <br>
    密码： <input type="password" name="password" required>
    <br>
    <input type="submit" value="登录">
    {{error}}

</form>

{% endcomment %}
<form action="#" method="post">
    {% csrf_token %}
    {{lf.username.label}}:{{lf.username}}
    <br>
    {{lf.username.help_text}}
    <br>
    {{lf.password.label}}:{{lf.password}}
    <br>
    {{lf.password.help_text}}
    <br>
    <input type="submit" value="登录">
    {{error}}
</form>
{% endblock %}

end/project1/bookdemo/templates/polls/other.html
<table>
        <tr><th>第一行第一列</th></tr>
        <tr><th>第一行第一列</th></tr>
        <tr><th>第一行第一列</th></tr>
    </table>

end/project1/bookdemo/templates/polls/regist.html
{% extends 'polls/base.html' %}
{% block title %}
    注册
{% endblock %}
{% block body %}
{% comment %}
<form action="#" method="post">
    {% csrf_token %}
    用户名: <input type="text" name="username" required>
    <br>
    密码： <input type="password" name="password" required>
    <br>
    重复密码： <input type="password" name="password2" required>
    <br>
    <input type="submit" value="注册">
    {{error}}

</form>
{% endcomment %}
<form action="#" method="post">
    {% csrf_token %}
    {{rf.username.label}}:{{rf.username}}
    <br>
    {{rf.username.help_text}}
    <br>
    {{rf.password.label}}:{{rf.password}}
    <br>
    {{rf.password.help_text}}
    <br>
    {{rf.password2.label}}:{{rf.password2}}
    <br>
    {{rf.password.help_text}}
    <br>
    <input type="submit" value="注册">
    {{error}}
</form>

{% endblock %}

end/project1/bookdemo/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block title %}
    投票结果
{% endblock %}
{% block body %}
            <h2>问题是: {{question.title}}</h2>

            <ul>
                <h3>得票情况</h3>
                {% for c in question.choices.all %}
                    <li>{{c.content}}   {{c.votes}} 票</li>
                {% endfor %}
            </ul>

            <a href="{% url 'polls:index' %}">返回</a>
{% endblock %}