end/project1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include


from django.http import HttpResponse


def index(request):
    return HttpResponse("这里是首页")


def list(request):
    return HttpResponse("这里是列表页")


def jsondata(request):
    return HttpResponse("{'name':'cxw','age':23}")
# 路由地址 每一个地址均需要绑定视图函数 视图函数给予页面返回
# mvt v 视图函数    作用：接受请求 处理数据 返回响应

urlpatterns = [
    path('admin/', admin.site.urls),
    # 1.使用path将bookset的路由进行包含
    path('polls/', include('polls.urls', namespace='polls')),
    path('download/', include('download.urls', namespace='download')),
    path('', include('bookset.urls', namespace='bookset')),

]

end/project1/bookdemo/bookset/urls.py
# 引入路由绑定函数
from django.conf.urls import url
from . import views


app_name = "bookset"

# 2.每一个路由文件中必须编写路由数组
urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^about/$", views.about, name="about"),
    # 使用正则分组可以向视图函数中传递参数
    # 正则分组中小括号匹配的内容会作为实参传递给视图函数
    url(r"detail/(\d+)/$", views.detail, name="detail"),
    url(r"delete/(\d+)/$", views.delete, name="delete"),
    url(r"delete_hero/(\d+)/$", views.delete_hero, name="delete_hero"),
    url(r"add_hero/(\d+)/$", views.add_hero, name="add_hero"),
    url(r"edithero/(\d+)/$", views.edithero, name="edithero"),
    url(r"add_book/$", views.add_book, name="add_book"),
    url(r"editbook/(\d+)/$", views.editbook, name="editbook"),
]

end/project1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # 如果在正则表达式中有正则分组  那么在视图中必须得有响应的形参
    # 如果正则分组有别名 那么形参名一定要和正则分组别名一致
    url(r'^detail/(?P<qid>\d+)/$',views.detail,name='detail'),
    url(r'^result/(\d+)/$',views.result,name='result'),
    url(r'^login/$',views.login,name='login'),
    url(r'^regist/$',views.regist,name='regist'),
    url(r'^logout/$',views.logout,name='logout')

    # url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^detail/(?P<qid>\d+)/$',views.DetailView.as_view(),name='detail'),
    # url(r'^result/(\d+)/$',views.ResultView.as_view(),name='result')
]

end/project1/bookdemo/bookset/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    """
    book继承了Model类。因为Model类拥有操作数据库的功能
    """
    title = models.CharField(max_length=20)
    pub_date = models.DateField(default="1983-06-01")
    price = models.FloatField(default=25)
    author = models.CharField(max_length=20,default="cxw")
    desc = models.CharField(max_length=50,null=True,blank=True,db_column="description")

    def __str__(self):
        return self.title


class Hero(models.Model):
    """
    hero继承了Model,也可以操作数据库
    """
    name = models.CharField(max_length=20)
    gender = models.CharField(max_length=6, choices=(('male', '男'), ('female', '女')), default='male')
    content = models.CharField(max_length=100)
    # book 是一对多中的外键 on_delete代表删除主表数据时如何做
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="heros")

    def __str__(self):
        return f"{self.name}=={self.gender}"


class UserManage(models.Manager):
    """自定义模型管理类 该模型不在具有objects对象"""
    def deleteByTelePhone(self, tele):
        # Django默认的objects 是Manage类型
        user = self.get(telephone=tele)
        user.delete()
        user.save()

    def createUser(self,tele):
        # self.model()可以获取模型类构造函数相当于User()
        user = self.model()
        user.telephone = tele
        user.save()


class User(models.Model):
    telephone = models.CharField(max_length=11, null=True, blank=True, verbose_name="手机号码")
    # 自定义过管理字段之后不再有objects 自定义了一个新的objects
    objects = UserManage()

    def __str__(self):
        return self.telephone

    class Meta:
        # 表明
        db_table = "用户类"
        ordering = ["-telephone"]
        # ordering页面进入模型类显示名字
        verbose_name = "用户模型类a"
        # admin 页面在应用下方显示的模型名
        verbose_name_plural = "用户模型类s"


class Acount(models.Model):
    username = models.CharField(max_length=20,verbose_name="用户名")
    password = models.CharField(max_length=20, verbose_name="密码")
    regist_date = models.DateField(auto_now_add=True, verbose_name="注册日期")


class Concact(models.Model):
    telephone = models.CharField(max_length=11,verbose_name="手机号")
    email = models.EmailField(default="973855683@qq.com")
    account = models.OneToOneField(Acount, on_delete=models.CASCADE, related_name="con")


class Article(models.Model):
    title = models.CharField(max_length=20, verbose_name="标题")
    summary = models.TextField(verbose_name="正文")


class Tag(models.Model):
    name = models.CharField(max_length=10, verbose_name="标签名")
    articles = models.ManyToManyField(Article, related_name="tags")

end/project1/bookdemo/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            名称:<input type="text" name="booktitile" placeholder="请输入书籍名称">
            <br>
            价格:<input type="text" name="bookprice" placeholder="请输入书籍价格">
            <br>
            出版日期:<input type="date" name="bookpub_date" placeholder="请输入书籍出版日期">
            <br>
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

end/project1/bookdemo/templates/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            英雄名字:<input type="text" name="heroname" placeholder="请输入角色名">
            <br>
            英雄技能:<input type="text" name="herocontent" placeholder="请输入角色绝招">
            <br>
            性别:<input type="radio" name="sex" value="female" checked> 女 <input type="radio" name="sex" value="male">男
            <br>
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

end/project1/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情</title>
</head>
<body>
    <h1>这里是详情页</h1>
    <div>
        <h2>书名:{{book.title}}</h2>
        <ul>
            {% for hero in book.hero_set.all %}
              <li>{{hero.name}}--{{hero.gender}}--{{hero.content}}<a href="{% url 'bookset:delete_hero' hero.id %}">删除</a></li>
              <li><a href="{% url 'bookset:edithero' hero.id %}">编辑英雄</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'bookset:add_hero' book.id %}">添加英雄</a>
    </div>
    <a href="/">返回列表页</a>
</body>
</html>

end/project1/bookdemo/templates/editbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑书籍</title>
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            名称:<input type="text" name="booktitle" value={{book.title}}>
            <br>
            价格:<input type="text" name="bookprice" value={{book.price}}>
            <br>
            出版日期:<input type="date" name="bookpub_date" value={{book.pub_date}}>
            <br>
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

end/project1/bookdemo/templates/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            英雄名字:<input type="text" name="heroname" value={{hero.name}}>
            <br>
            英雄技能:<input type="text" name="herocontent" value={{hero.content}}>
            <br>
            {% if hero.gender == 'male' %}
            性别:<input type="radio" name="sex" value="female"> 女 <input type="radio" name="sex" value="male" checked>男
            {% else %}
            性别:<input type="radio" name="sex" value="female" checked> 女 <input type="radio" name="sex" value="male">男
            {% endif %}
            <br>
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

end/project1/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <!--  这里是普通的注释        -->
        {# 这里是django模板注释 #}

        <h1 class="center">这里是首页   <a href="{% url 'polls:index' %}">进入投票应用</a>      </h1>


        <div>
            <div class="center">
                <img src="/static/img/图片.gif" alt="">
            </div>


            <h2>共有书籍({{books.count}})</h2>
            <h2>共有书籍({{books|length}})</h2>
            <h2>{{name|upper|join:'++'|length}}</h2>
            {# 指明得到的name1是安全的 可以让浏览器解释 #}
            <h2>{{name1|safe}}</h2>

            {# django会默认开启自动转义  不翻译html格式代码   #}
            {% autoescape off %}
                <h2>{{name1}}</h2>
                <h2>{{name1}}</h2>

                <h2>{{name1}}</h2>
            {% endautoescape %}

            <ul>
                {% for book in books  %}
                    <li>
                        {# <a href="/detail/{{book.id}}/"> <li>{{book.id}} -- {{book.title}} -- {{book.price}} -- {{book.pub_date}}</li>  </a> #}

                        <a href="{% url 'bookset:detail' book.id %}"> {{book.id}} -- {{book.title}} -- {{book.price}} -- {{book.pub_date}}    </a>

                        <a href="{% url 'bookset:delete' book.id %}">删除</a>
                    </li>
                {% endfor %}

            </ul>

              <h2><a href="{% url 'bookset:add_book' %}">添加书籍</a>  </h2>
        </div>

        {% for smallb in smallbook %}
            <li>{{smallb.title}}</li>
        {% empty %}
            <li>当前列表没有对象</li>
        {% endfor %}

        <a href="http://127.0.0.1:8000/download/require.txt">下载 reuire</a>
        <a href="http://127.0.0.1:8000/download/db.sqlite3">下载 db</a>
    </div>
</body>
</html>